### ISSUE TITLE
value error while loading data from generator

### ISSUE THREAD

**Issue by pooraniravindhiran** [jcborges/DeepStack#16]
Hey,

I tried to create a kerasMember using flow_from_dataframe option and I passed the data generators as arguments into KerasMember function. But, it is raising the value error. So, this package can only use training data when passed as tuples?

**Comment by pooraniravindhiran** [comment]
Same as previous issue.

**Comment by ma7555** [comment]
@pooraniravi, I guess you are correct regarding validation and test sets (which are training and validation for the meta-learner) as technically the meta-learner is a decision tree classifier which can not learn in batches as MLP. so from my point of view, there is no way you can make a decision tree fit without seeing all data at once (to decide root splits, etc..)

Please refer here: https://scikit-learn.org/0.15/modules/scaling_strategies.html#incremental-learning

I have given this repo a try but unfortunately it seems to be unmaintained and I am facing issues as well.
